version: '2'

services:

  nginx:
    image: nginx:latest
    container_name: reverse_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../../static:/www/data/static 
    links:
      - node1:node1
    depends_on: 
      - node1
    ports:
      - "8080:80"
    networks:
      - app-network

  node1:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - ../src:/usr/src/app
    ports:
      - "3000"
    environment:
      - INSTANCE=node1
    links:
      - mongo:mongo
      - couchdb:couchdb
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db
    logging:
      driver: none

  couchdb:
    image: couchdb:latest
    ports:
      - "5984:5984"
    networks:
      - app-network
    environment:
      - 'COUCHDB_USER=admin'
      - 'COUCHDB_PASSWORD=admin'
    volumes:
      - couch-data:/opt/couchdb/data
    logging:
      driver: none

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
  couch-data:
    driver: local
